export const talks = [
  {
    year: "2020",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "Webinale",
        date: "May 2020",
        location: "Berlin, Germany",
        link: "https://webinale.de/en/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Willhaben Markup Language WHML",
        conference: "Vienna JS",
        date: "Feb 2020",
        location: "Vienna, Austria",
        link: "https://viennajs.org/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/willhaben-markup-language-whml",
      },
    ],
  },
  {
    year: "2019",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "Heisenbug Conf",
        date: "Dec 2019",
        location: "Moscow, Russia",
        link: "https://heisenbug-moscow.ru/en/",
        video: "https://www.youtube.com/watch?v=GyXkH5ZmSfk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Siberia",
        date: "Nov 2019",
        location: "Novosibirsk, Russia",
        link: "https://gdg-siberia.com/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "WebClerks",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://webclerks.at/",
        video: "https://youtu.be/ucLEMETfrTA?t=14220",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Vienna",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "React Vienna",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://twitter.com/reactvienna",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "JSConf Colombia",
        date: "Oct 2019",
        location: "Medellín, Colombia",
        link: "http://jsconf.co/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "AXSChat",
        date: "Oct 2019",
        location: "YouTube",
        link: "http://axschat.com/",
        video: "https://www.youtube.com/watch?v=JFaS1JGO71w",
        slides: "",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Accessibility talks",
        date: "Aug 2019",
        location: "YouTube",
        link: "https://www.youtube.com/c/accessibilitytalks",
        video: "https://www.youtube.com/watch?v=Nq6UhL_QvZk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
    ],
  },
  {
    year: "2018",
    talks: [
      {
        title: "How does your website 'sound' like?",
        conference: "UX Vienna",
        date: "Dec 2018",
        location: "Vienna, Austria",
        link: "https://uxvienna.at/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "How does your website 'sound' like?",
        conference: "DevFest Vienna",
        date: "Nov 2018",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "https://www.youtube.com/watch?v=yKYA-7tczuk",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "Willhaben Markup Language WHML",
        conference: "Vienna JS",
        date: "May 2018",
        location: "Vienna, Austria",
        link: "https://viennajs.org/",
        video: "https://www.youtube.com/watch?v=tJXzyHHh4pc",
        slides:
          "https://speakerdeck.com/bolonio/willhaben-markup-language-whml",
      },
    ],
  },
]
